[MIG] membership_prorrate: Migrated to 10.0
OCA/vertical-association pull request #30
Opened 2017-05-17 10:43 UTC by chienandalu

cc @Tecnativa

2017-06-07 08:13 UTC, pedrobaeza requested changes

2017-06-07 08:13 UTC, pedrobaeza commented on membership_prorrate/__manifest__.py
>                'Serv. Tecnol. Avanzados - Pedro M. Baeza, '
Remove old authors and put only `Tecnativa`

2017-06-07 08:13 UTC, pedrobaeza commented on membership_prorrate/__manifest__.py
> -    'installable': False,
Switch to True instead of removing it.

2017-06-07 08:13 UTC, pedrobaeza commented on membership_prorrate/tests/test_membership_prorrate.py
> +            'account.data_account_type_expenses').id)], limit=1).id
Use directly `self.product.property_account_income_id` instead of searching a demo account (which any way can be got directly with `self.env.ref`)

2017-06-08 18:29 UTC, chienandalu commented on membership_prorrate/tests/test_membership_prorrate.py
> +            'account.data_account_type_expenses').id)], limit=1).id
I had `self.product.property_account_income_id` empty so I used `self.partner.property_account_receivable_id`. Is it valid for the purpose of this test?

2017-06-08 18:47 UTC, pedrobaeza commented on membership_prorrate/tests/test_membership_prorrate.py
> +            'account.data_account_type_expenses').id)], limit=1).id
Well, it can serve, as it's an account and we don't need accounting correctness.

2017-06-08 18:48 UTC, pedrobaeza requested changes

2017-06-08 18:48 UTC, pedrobaeza commented on membership_prorrate/tests/test_membership_prorrate.py
> +        invoice_line_account = self.partner.property_account_receivable_id.id
Call it `account` and use it in both places.

2017-06-08 18:48 UTC, pedrobaeza commented on membership_prorrate/tests/test_membership_prorrate.py
> +            'account_id': self.partner.property_account_receivable_id.id,
Use here `account`

2017-06-09 08:16 UTC, chienandalu commented
@pedrobaeza changes done and green already. Anyway I'm missing the module's history. I'll try to recover prior to merge.

2017-06-09 09:51 UTC, pedrobaeza approved these changes

2017-06-09 09:51 UTC, pedrobaeza commented
@rafaelbn please review

2017-06-12 17:27 UTC, rafaelbn approved these changes
Tested in runbot 👍

2017-06-12 17:27 UTC, rafaelbn commented on membership_prorrate/README.rst
>  * Pedro M. Baeza <pedro.baeza@serviciosbaeza.com>
Change email to pedro.baeza@tecnativa.com

2017-06-12 18:10 UTC, merged