[10.0][fix] membership_extension: add security group to menu
OCA/vertical-association pull request #53
Opened 2017-12-20 17:52 UTC by luismontalba

- Add access right to the main menu ("members") to employees group, avoiding restriction for only accountants when the association module is installed.

2017-12-20 17:56 UTC, pedrobaeza commented
This is not security. It's changing a menu field, so it should go in /views/.

Any way, this is not what we have talked. I want a new security group for granting specifically that. And check all ACLs needed to that group. Imagine you only have that new group, and you need to access the same objects in that menu than any other role with that permission.

2017-12-21 18:39 UTC, chienandalu commented
@pedrobaeza I've made the security group, and gave permissions so a user with just this group could access to the whole features of the  membership application.

2017-12-21 20:41 UTC, pedrobaeza requested changes
Are you sure you don't need more permissions?

2017-12-21 20:41 UTC, pedrobaeza commented on membership_extension/__manifest__.py
> +    "version": "10.0.1.1.4",
Change version to 10.0.1.2.0

2017-12-21 20:41 UTC, pedrobaeza commented on membership_extension/security/membership_security.xml
> +        <field name="name">Membership manager</field>
Call it only `Manager`, as the display name will be `Membership / Manager`

2017-12-22 09:01 UTC, chienandalu commented
@pedrobaeza Changes done (added one ACL more) and tested that a user with just **Membership manager**, **Employee** and **Contact creation** permissions can do all member operations except billing (for wich the **Billing** permission would be granted)

2017-12-22 09:06 UTC, pedrobaeza approved these changes

2017-12-22 12:23 UTC, rafaelbn approved these changes
Functionally tested in runbot 👍

2017-12-22 12:23 UTC, rafaelbn commented
Thanks @chienandalu

2017-12-22 12:23 UTC, merged