[MIG] membership_prorate_variable_period: Migration to 11.0
OCA/vertical-association pull request #59
Opened 2018-06-06 16:29 UTC by chienandalu

Helper module for making the prorate correctly when you are dealing with
variable periods in your memberships, which functionality is provided by
the module *membership_variable_period*.

cc @Tecnativa

2018-06-07 08:25 UTC, pedrobaeza commented
Please rebase

2018-06-08 09:02 UTC, chienandalu commented
@pedrobaeza All green
@rafaelbn Please review

2018-06-08 14:09 UTC, pedrobaeza requested changes

2018-06-08 14:09 UTC, pedrobaeza commented on membership_prorate_variable_period/readme/CREDITS.rst
> +[ This file is optional and contains additional credits, other than
Remove this file

2018-06-08 14:12 UTC, chienandalu commented
@pedrobaeza Done

2018-06-08 14:16 UTC, pedrobaeza approved these changes

2018-06-11 15:13 UTC, yajo approved these changes

2018-06-11 15:13 UTC, Yajo commented on membership_prorate_variable_period/models/account_invoice.py
> +import datetime
Fix import order

2018-06-12 10:59 UTC, rafaelbn approved these changes
Tested

2018-06-12 10:59 UTC, merged